In [1]:
s="Hi there sam!"
s.split()

['Hi', 'there', 'sam!']

In [2]:
planet="Earth"
diameter="12742"
print("The diameter of{} is {} kilometers.".format(planet,diameter))

The diameter ofEarth is 12742 kilometers.


In [3]:
d= {'k1':[1,2,3,{'trichy':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

d ['k1'][3]['trichy'][3]['target'][3]

'hello'

In [5]:
import numpy as np

In [6]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [7]:
np.ones(10)*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [8]:
print(np.arange(20,36,2))

[20 22 24 26 28 30 32 34]


In [9]:
np.arange(0,9).reshape((3,3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [10]:
a= np.array([1,2,3])
b= np.array([4,5,6])
np.concatenate((a,b))

array([1, 2, 3, 4, 5, 6])

In [12]:
import pandas as pd

In [13]:
data={'name':['tom','jerry','sam'],
     'age':[15,12,14]}

pd.DataFrame(data)

name  age
0    tom   15
1  jerry   12
2    sam   14

In [14]:
import  datetime

In [15]:
pd.to_datetime(pd.Series(["Jan 1,2022","2023-02-10",]))

0   2022-01-01
1   2023-02-10
dtype: datetime64[ns]

In [16]:
lists=[[1,'aaa',22],[2,'bbb',25],[3,'ccc',24]]
pd.DataFrame(lists)

0    1   2
0  1  aaa  22
1  2  bbb  25
2  3  ccc  24